name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  push-acr:
    runs-on: ubuntu-latest
    services:
      verdaccio:
        image: verdaccio/verdaccio
        ports:
          - 4873:4873
    steps:
      - name: Checkout nocobase/nocobase
        uses: actions/checkout@v3
        with:
          repository: nocobase/nocobase
          ref: main

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: packages/plugins/@nocobase/plugin-boilerplate
      - name: add plugin to git
        run: rm -rf packages/plugins/@nocobase/plugin-boilerplate/.git &&  git config --global user.email "you@example.com"  &&  git config --global user.name "Your Name" && git add -A && git commit -m "tmp commit"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            nocobase/nocobase
          tags: |
            type=raw,value=plugin-boilerplate
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REGISTRY }}
          username: ${{ secrets.ALI_DOCKER_USERNAME }}
          password: ${{ secrets.ALI_DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          build-args: |
            VERDACCIO_URL=http://localhost:4873/
            COMMIT_HASH=${GITHUB_SHA}
            APPEND_PRESET_LOCAL_PLUGINS=boilerplate
            BEFORE_PACK_NOCOBASE=yarn add @nocobase/plugin-boilerplate -W
          push: true
          tags: ${{ secrets.ALI_DOCKER_REGISTRY }}/${{ steps.meta.outputs.tags }}
      - name: Deploy NocoBase
        env:
          IMAGE_TAG: ${{ steps.meta.outputs.tags }}
        run: |
          curl --retry 2 --location --request POST "${{secrets.NOCOBASE_DEPLOY_HOST}}plugin-boilerplate" \
            --header 'Content-Type: application/json' \
            -d "{
                \"tag\": \"plugin-boilerplate\",
                \"dialect\": \"postgres\"
            }"
